### ISSUE TITLE
Error when trying to make a heatmap

### ISSUE THREAD

**Issue by Sanewsg** [Rong-Zh/GWLD-R#1]
Able to produce an LD matrix but Heatmap command gives error;
**Code**
data<-read.delim("MySNP.txt")
data<-codegeno(data,sep="")
Info<-read.delim("MyInfo.txt")
result<-GWLD(data,method="r^2",cores=1)
write.csv(result,"G://…/Result.csv",quote=F)

#Plot HeatMap
p <- HeatMap(data,method="r^2",cores = 1,SnpPosition=Info$POS,SnpName=Info$ID,color="YellowToRed",showLDvalues = F)

**Error message**
Error in ans[npos] <- rep(no, length.out = len)[npos] :    replacement has length zero In addition: Warning message: In rep(no, length.out = len) : 'x' is NULL so the result will be NULL
--
 The Duck example data runs okay. Any ideas on what to check please.

**Comment by Rong-Zh** [comment]
The problem has been solved. Use devtools::install_github("Rong-Zh/GWLD/GWLD-R") to install the new version. At the same time, the [example ](https://github.com/Rong-Zh/GWLD/blob/master/example/example.R)has been updated.
